/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AgreementsRouteImport } from './routes/agreements'
import { Route as AiCommandRouteImport } from './routes/ai-command'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as EmailRouteImport } from './routes/email'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as MyFutureRouteImport } from './routes/my-future'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignaturesRouteImport } from './routes/signatures'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as ApiBulkMailProgressRouteImport } from './routes/api/bulk-mail-progress'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiFutureBriefRouteImport } from './routes/api/future-brief'
import { Route as ApiKeywordsRouteImport } from './routes/api/keywords'
import { Route as ApiLeadFinderStatsRouteImport } from './routes/api/lead-finder-stats'
import { Route as ApiLeadSheetsProxyRouteImport } from './routes/api/lead-sheets-proxy'
import { Route as ApiKeywordsIdRouteImport } from './routes/api/keywords.$id'
import { Route as ApiKeywordsAiRouteImport } from './routes/api/keywords.ai'
import { Route as ApiKeywordsNextRouteImport } from './routes/api/keywords.next'
import { Route as ApiKeywordsIdUsageRouteImport } from './routes/api/keywords.$id.usage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementsRoute = AgreementsRouteImport.update({
  id: '/agreements',
  path: '/agreements',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCommandRoute = AiCommandRouteImport.update({
  id: '/ai-command',
  path: '/ai-command',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const MyFutureRoute = MyFutureRouteImport.update({
  id: '/my-future',
  path: '/my-future',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignaturesRoute = SignaturesRouteImport.update({
  id: '/signatures',
  path: '/signatures',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBulkMailProgressRoute = ApiBulkMailProgressRouteImport.update({
  id: '/api/bulk-mail-progress',
  path: '/api/bulk-mail-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFutureBriefRoute = ApiFutureBriefRouteImport.update({
  id: '/api/future-brief',
  path: '/api/future-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeywordsRoute = ApiKeywordsRouteImport.update({
  id: '/api/keywords',
  path: '/api/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadFinderStatsRoute = ApiLeadFinderStatsRouteImport.update({
  id: '/api/lead-finder-stats',
  path: '/api/lead-finder-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadSheetsProxyRoute = ApiLeadSheetsProxyRouteImport.update({
  id: '/api/lead-sheets-proxy',
  path: '/api/lead-sheets-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeywordsIdRoute = ApiKeywordsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiKeywordsRoute,
} as any)
const ApiKeywordsAiRoute = ApiKeywordsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => ApiKeywordsRoute,
} as any)
const ApiKeywordsNextRoute = ApiKeywordsNextRouteImport.update({
  id: '/next',
  path: '/next',
  getParentRoute: () => ApiKeywordsRoute,
} as any)
const ApiKeywordsIdUsageRoute = ApiKeywordsIdUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => ApiKeywordsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agreements': typeof AgreementsRoute
  '/ai-command': typeof AiCommandRoute
  '/ai-insights': typeof AiInsightsRoute
  '/calendar': typeof CalendarRoute
  '/calls': typeof CallsRoute
  '/crm': typeof CrmRoute
  '/email': typeof EmailRoute
  '/employees': typeof EmployeesRoute
  '/finance': typeof FinanceRoute
  '/forecast': typeof ForecastRoute
  '/habits': typeof HabitsRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/meetings': typeof MeetingsRoute
  '/my-future': typeof MyFutureRoute
  '/notifications': typeof NotificationsRoute
  '/planner': typeof PlannerRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signatures': typeof SignaturesRoute
  '/tasks': typeof TasksRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/bulk-mail-progress': typeof ApiBulkMailProgressRoute
  '/api/chat': typeof ApiChatRoute
  '/api/future-brief': typeof ApiFutureBriefRoute
  '/api/keywords': typeof ApiKeywordsRouteWithChildren
  '/api/lead-finder-stats': typeof ApiLeadFinderStatsRoute
  '/api/lead-sheets-proxy': typeof ApiLeadSheetsProxyRoute
  '/api/keywords/$id': typeof ApiKeywordsIdRouteWithChildren
  '/api/keywords/ai': typeof ApiKeywordsAiRoute
  '/api/keywords/next': typeof ApiKeywordsNextRoute
  '/api/keywords/$id/usage': typeof ApiKeywordsIdUsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agreements': typeof AgreementsRoute
  '/ai-command': typeof AiCommandRoute
  '/ai-insights': typeof AiInsightsRoute
  '/calendar': typeof CalendarRoute
  '/calls': typeof CallsRoute
  '/crm': typeof CrmRoute
  '/email': typeof EmailRoute
  '/employees': typeof EmployeesRoute
  '/finance': typeof FinanceRoute
  '/forecast': typeof ForecastRoute
  '/habits': typeof HabitsRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/meetings': typeof MeetingsRoute
  '/my-future': typeof MyFutureRoute
  '/notifications': typeof NotificationsRoute
  '/planner': typeof PlannerRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signatures': typeof SignaturesRoute
  '/tasks': typeof TasksRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/bulk-mail-progress': typeof ApiBulkMailProgressRoute
  '/api/chat': typeof ApiChatRoute
  '/api/future-brief': typeof ApiFutureBriefRoute
  '/api/keywords': typeof ApiKeywordsRouteWithChildren
  '/api/lead-finder-stats': typeof ApiLeadFinderStatsRoute
  '/api/lead-sheets-proxy': typeof ApiLeadSheetsProxyRoute
  '/api/keywords/$id': typeof ApiKeywordsIdRouteWithChildren
  '/api/keywords/ai': typeof ApiKeywordsAiRoute
  '/api/keywords/next': typeof ApiKeywordsNextRoute
  '/api/keywords/$id/usage': typeof ApiKeywordsIdUsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agreements': typeof AgreementsRoute
  '/ai-command': typeof AiCommandRoute
  '/ai-insights': typeof AiInsightsRoute
  '/calendar': typeof CalendarRoute
  '/calls': typeof CallsRoute
  '/crm': typeof CrmRoute
  '/email': typeof EmailRoute
  '/employees': typeof EmployeesRoute
  '/finance': typeof FinanceRoute
  '/forecast': typeof ForecastRoute
  '/habits': typeof HabitsRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/meetings': typeof MeetingsRoute
  '/my-future': typeof MyFutureRoute
  '/notifications': typeof NotificationsRoute
  '/planner': typeof PlannerRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signatures': typeof SignaturesRoute
  '/tasks': typeof TasksRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/bulk-mail-progress': typeof ApiBulkMailProgressRoute
  '/api/chat': typeof ApiChatRoute
  '/api/future-brief': typeof ApiFutureBriefRoute
  '/api/keywords': typeof ApiKeywordsRouteWithChildren
  '/api/lead-finder-stats': typeof ApiLeadFinderStatsRoute
  '/api/lead-sheets-proxy': typeof ApiLeadSheetsProxyRoute
  '/api/keywords/$id': typeof ApiKeywordsIdRouteWithChildren
  '/api/keywords/ai': typeof ApiKeywordsAiRoute
  '/api/keywords/next': typeof ApiKeywordsNextRoute
  '/api/keywords/$id/usage': typeof ApiKeywordsIdUsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/agreements'
    | '/ai-command'
    | '/ai-insights'
    | '/calendar'
    | '/calls'
    | '/crm'
    | '/email'
    | '/employees'
    | '/finance'
    | '/forecast'
    | '/habits'
    | '/invoices'
    | '/leads'
    | '/meetings'
    | '/my-future'
    | '/notifications'
    | '/planner'
    | '/products'
    | '/projects'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/signatures'
    | '/tasks'
    | '/whatsapp'
    | '/api/bulk-mail-progress'
    | '/api/chat'
    | '/api/future-brief'
    | '/api/keywords'
    | '/api/lead-finder-stats'
    | '/api/lead-sheets-proxy'
    | '/api/keywords/$id'
    | '/api/keywords/ai'
    | '/api/keywords/next'
    | '/api/keywords/$id/usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/agreements'
    | '/ai-command'
    | '/ai-insights'
    | '/calendar'
    | '/calls'
    | '/crm'
    | '/email'
    | '/employees'
    | '/finance'
    | '/forecast'
    | '/habits'
    | '/invoices'
    | '/leads'
    | '/meetings'
    | '/my-future'
    | '/notifications'
    | '/planner'
    | '/products'
    | '/projects'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/signatures'
    | '/tasks'
    | '/whatsapp'
    | '/api/bulk-mail-progress'
    | '/api/chat'
    | '/api/future-brief'
    | '/api/keywords'
    | '/api/lead-finder-stats'
    | '/api/lead-sheets-proxy'
    | '/api/keywords/$id'
    | '/api/keywords/ai'
    | '/api/keywords/next'
    | '/api/keywords/$id/usage'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/agreements'
    | '/ai-command'
    | '/ai-insights'
    | '/calendar'
    | '/calls'
    | '/crm'
    | '/email'
    | '/employees'
    | '/finance'
    | '/forecast'
    | '/habits'
    | '/invoices'
    | '/leads'
    | '/meetings'
    | '/my-future'
    | '/notifications'
    | '/planner'
    | '/products'
    | '/projects'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/signatures'
    | '/tasks'
    | '/whatsapp'
    | '/api/bulk-mail-progress'
    | '/api/chat'
    | '/api/future-brief'
    | '/api/keywords'
    | '/api/lead-finder-stats'
    | '/api/lead-sheets-proxy'
    | '/api/keywords/$id'
    | '/api/keywords/ai'
    | '/api/keywords/next'
    | '/api/keywords/$id/usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AgreementsRoute: typeof AgreementsRoute
  AiCommandRoute: typeof AiCommandRoute
  AiInsightsRoute: typeof AiInsightsRoute
  CalendarRoute: typeof CalendarRoute
  CallsRoute: typeof CallsRoute
  CrmRoute: typeof CrmRoute
  EmailRoute: typeof EmailRoute
  EmployeesRoute: typeof EmployeesRoute
  FinanceRoute: typeof FinanceRoute
  ForecastRoute: typeof ForecastRoute
  HabitsRoute: typeof HabitsRoute
  InvoicesRoute: typeof InvoicesRoute
  LeadsRoute: typeof LeadsRoute
  MeetingsRoute: typeof MeetingsRoute
  MyFutureRoute: typeof MyFutureRoute
  NotificationsRoute: typeof NotificationsRoute
  PlannerRoute: typeof PlannerRoute
  ProductsRoute: typeof ProductsRoute
  ProjectsRoute: typeof ProjectsRoute
  QuotationsRoute: typeof QuotationsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SignaturesRoute: typeof SignaturesRoute
  TasksRoute: typeof TasksRoute
  WhatsappRoute: typeof WhatsappRoute
  ApiBulkMailProgressRoute: typeof ApiBulkMailProgressRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiFutureBriefRoute: typeof ApiFutureBriefRoute
  ApiKeywordsRoute: typeof ApiKeywordsRouteWithChildren
  ApiLeadFinderStatsRoute: typeof ApiLeadFinderStatsRoute
  ApiLeadSheetsProxyRoute: typeof ApiLeadSheetsProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreements': {
      id: '/agreements'
      path: '/agreements'
      fullPath: '/agreements'
      preLoaderRoute: typeof AgreementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-command': {
      id: '/ai-command'
      path: '/ai-command'
      fullPath: '/ai-command'
      preLoaderRoute: typeof AiCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-future': {
      id: '/my-future'
      path: '/my-future'
      fullPath: '/my-future'
      preLoaderRoute: typeof MyFutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signatures': {
      id: '/signatures'
      path: '/signatures'
      fullPath: '/signatures'
      preLoaderRoute: typeof SignaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bulk-mail-progress': {
      id: '/api/bulk-mail-progress'
      path: '/api/bulk-mail-progress'
      fullPath: '/api/bulk-mail-progress'
      preLoaderRoute: typeof ApiBulkMailProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/future-brief': {
      id: '/api/future-brief'
      path: '/api/future-brief'
      fullPath: '/api/future-brief'
      preLoaderRoute: typeof ApiFutureBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keywords': {
      id: '/api/keywords'
      path: '/api/keywords'
      fullPath: '/api/keywords'
      preLoaderRoute: typeof ApiKeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead-finder-stats': {
      id: '/api/lead-finder-stats'
      path: '/api/lead-finder-stats'
      fullPath: '/api/lead-finder-stats'
      preLoaderRoute: typeof ApiLeadFinderStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead-sheets-proxy': {
      id: '/api/lead-sheets-proxy'
      path: '/api/lead-sheets-proxy'
      fullPath: '/api/lead-sheets-proxy'
      preLoaderRoute: typeof ApiLeadSheetsProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keywords/$id': {
      id: '/api/keywords/$id'
      path: '/$id'
      fullPath: '/api/keywords/$id'
      preLoaderRoute: typeof ApiKeywordsIdRouteImport
      parentRoute: typeof ApiKeywordsRoute
    }
    '/api/keywords/ai': {
      id: '/api/keywords/ai'
      path: '/ai'
      fullPath: '/api/keywords/ai'
      preLoaderRoute: typeof ApiKeywordsAiRouteImport
      parentRoute: typeof ApiKeywordsRoute
    }
    '/api/keywords/next': {
      id: '/api/keywords/next'
      path: '/next'
      fullPath: '/api/keywords/next'
      preLoaderRoute: typeof ApiKeywordsNextRouteImport
      parentRoute: typeof ApiKeywordsRoute
    }
    '/api/keywords/$id/usage': {
      id: '/api/keywords/$id/usage'
      path: '/usage'
      fullPath: '/api/keywords/$id/usage'
      preLoaderRoute: typeof ApiKeywordsIdUsageRouteImport
      parentRoute: typeof ApiKeywordsIdRoute
    }
  }
}

interface ApiKeywordsIdRouteChildren {
  ApiKeywordsIdUsageRoute: typeof ApiKeywordsIdUsageRoute
}

const ApiKeywordsIdRouteChildren: ApiKeywordsIdRouteChildren = {
  ApiKeywordsIdUsageRoute: ApiKeywordsIdUsageRoute,
}

const ApiKeywordsIdRouteWithChildren = ApiKeywordsIdRoute._addFileChildren(
  ApiKeywordsIdRouteChildren,
)

interface ApiKeywordsRouteChildren {
  ApiKeywordsIdRoute: typeof ApiKeywordsIdRouteWithChildren
  ApiKeywordsAiRoute: typeof ApiKeywordsAiRoute
  ApiKeywordsNextRoute: typeof ApiKeywordsNextRoute
}

const ApiKeywordsRouteChildren: ApiKeywordsRouteChildren = {
  ApiKeywordsIdRoute: ApiKeywordsIdRouteWithChildren,
  ApiKeywordsAiRoute: ApiKeywordsAiRoute,
  ApiKeywordsNextRoute: ApiKeywordsNextRoute,
}

const ApiKeywordsRouteWithChildren = ApiKeywordsRoute._addFileChildren(
  ApiKeywordsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AgreementsRoute: AgreementsRoute,
  AiCommandRoute: AiCommandRoute,
  AiInsightsRoute: AiInsightsRoute,
  CalendarRoute: CalendarRoute,
  CallsRoute: CallsRoute,
  CrmRoute: CrmRoute,
  EmailRoute: EmailRoute,
  EmployeesRoute: EmployeesRoute,
  FinanceRoute: FinanceRoute,
  ForecastRoute: ForecastRoute,
  HabitsRoute: HabitsRoute,
  InvoicesRoute: InvoicesRoute,
  LeadsRoute: LeadsRoute,
  MeetingsRoute: MeetingsRoute,
  MyFutureRoute: MyFutureRoute,
  NotificationsRoute: NotificationsRoute,
  PlannerRoute: PlannerRoute,
  ProductsRoute: ProductsRoute,
  ProjectsRoute: ProjectsRoute,
  QuotationsRoute: QuotationsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SignaturesRoute: SignaturesRoute,
  TasksRoute: TasksRoute,
  WhatsappRoute: WhatsappRoute,
  ApiBulkMailProgressRoute: ApiBulkMailProgressRoute,
  ApiChatRoute: ApiChatRoute,
  ApiFutureBriefRoute: ApiFutureBriefRoute,
  ApiKeywordsRoute: ApiKeywordsRouteWithChildren,
  ApiLeadFinderStatsRoute: ApiLeadFinderStatsRoute,
  ApiLeadSheetsProxyRoute: ApiLeadSheetsProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
